export interface CategoryList {
  id: number;
  categories: string[];
}

export const VALID_LETTERS = 'ABCDEFGHIJKLMNOPRSTW'.split('');

export const CATEGORY_LISTS: CategoryList[] = [
  {
    id: 1,
    categories: [
      "A Boy's Name",
      'U.S. Cities',
      'Things That Are Cold',
      'School Supplies',
      'TV Shows',
      'Fruits',
      'Animals',
      'Things in a Kitchen',
      'Sports',
      'Occupations',
      'Clothing',
      'Vegetables',
    ],
  },
  {
    id: 2,
    categories: [
      "A Girl's Name",
      'Countries',
      'Things That Are Soft',
      'Breakfast Foods',
      'Movies',
      'Musical Instruments',
      'Colors',
      'Things at a Beach',
      'Hobbies',
      'Book Titles',
      'Desserts',
      'Car Brands',
    ],
  },
  {
    id: 3,
    categories: [
      'Famous People',
      'Things in a Bedroom',
      'Restaurants',
      'Toys',
      'Songs',
      'Things That Grow',
      'College Majors',
      'Candy Bars',
      'Things in a Park',
      'Magazines',
      'Pizza Toppings',
      'Holidays',
    ],
  },
  {
    id: 4,
    categories: [
      'Things in a Bathroom',
      'Insects',
      'Vacation Spots',
      'Snack Foods',
      'Video Games',
      'Things at a Zoo',
      'Flowers',
      'Beverages',
      'Things in a Garage',
      'Superheroes',
      'Languages',
      'Dances',
    ],
  },
  {
    id: 5,
    categories: [
      'Things in a Hospital',
      'World Leaders',
      'Board Games',
      'Things That Are Round',
      'Cartoon Characters',
      'Ice Cream Flavors',
      'Things at a Wedding',
      'Dog Breeds',
      'Stores',
      'Things in Space',
      'Sandwiches',
      'Musical Groups',
    ],
  },
  {
    id: 6,
    categories: [
      'Things in a Classroom',
      'Athletes',
      'Things That Are Hot',
      'Pasta Dishes',
      'Things at a Circus',
      'Trees',
      'Excuses for Being Late',
      'Things in a Wallet',
      'Fictional Characters',
      'Things at a Grocery Store',
      'Emotions',
      'Things with Wheels',
    ],
  },
  {
    id: 7,
    categories: [
      'Things in an Office',
      'Bodies of Water',
      'Things That Are Sticky',
      'Breakfast Cereals',
      'Things at a Concert',
      'Herbs and Spices',
      'Things You Throw Away',
      'Mythological Creatures',
      'Things at a Campsite',
      'Household Chores',
      'Things with Buttons',
      'Nicknames',
    ],
  },
  {
    id: 8,
    categories: [
      'Things at a Party',
      'Historical Events',
      'Things That Are Loud',
      'Seafood',
      'Things in a Toolbox',
      'Birds',
      'Things You Do Before Bed',
      'Brands',
      'Things at a Museum',
      'Things Made of Metal',
      'Fairy Tale Characters',
      'Things You Read',
    ],
  },
  {
    id: 9,
    categories: [
      'Things at a Playground',
      'Scientists',
      'Things That Are Scary',
      'Baked Goods',
      'Things in a Purse',
      'Reptiles',
      'Things You Do on Vacation',
      'Websites',
      'Things at a Farm',
      'Things Made of Wood',
      'Villains',
      'Things You Collect',
    ],
  },
  {
    id: 10,
    categories: [
      'Things at an Airport',
      'Inventions',
      'Things That Are Shiny',
      'Condiments',
      'Things in a Gym',
      'Fish',
      'Things You Do on Weekends',
      'Apps',
      'Things at a Library',
      'Things Made of Glass',
      'Comedians',
      'Things You Wear on Your Head',
    ],
  },
];

export const TOTAL_ROUNDS = 3;
export const ROUND_TIMER_SECONDS = 90;
export const CATEGORIES_PER_LIST = 12;
export const MAX_PLAYERS = 6;
