export type AIDifficulty = 'easy' | 'medium' | 'hard';

const WORD_BANK: Record<string, string[]> = {
  name: [
    'Aaron', 'Abigail', 'Adam', 'Alice', 'Amanda', 'Andrew', 'Anna', 'Anthony',
    'Barbara', 'Benjamin', 'Beth', 'Blake', 'Brad', 'Brian', 'Bridget', 'Bruce',
    'Carl', 'Caroline', 'Chad', 'Charlie', 'Chris', 'Claire', 'Craig', 'Crystal',
    'Daniel', 'Danielle', 'David', 'Debra', 'Derek', 'Diana', 'Donald', 'Dorothy',
    'Edward', 'Eleanor', 'Elizabeth', 'Emily', 'Eric', 'Ethan', 'Eva', 'Evelyn',
    'Frank', 'Frances', 'Frederick', 'Faith', 'Felix', 'Fiona',
    'Gary', 'George', 'Gloria', 'Grace', 'Grant', 'Greg', 'Gwen',
    'Harold', 'Heather', 'Helen', 'Henry', 'Holly', 'Howard', 'Hugo',
    'Ian', 'Irene', 'Isaac', 'Ivan', 'Ivy',
    'Jack', 'James', 'Jane', 'Jason', 'Jennifer', 'Jessica', 'John', 'Julia',
    'Karen', 'Kate', 'Keith', 'Kelly', 'Ken', 'Kevin', 'Kim', 'Kyle',
    'Larry', 'Laura', 'Leo', 'Linda', 'Lisa', 'Logan', 'Louis', 'Lucy',
    'Marcus', 'Margaret', 'Maria', 'Mark', 'Martha', 'Michael', 'Michelle', 'Monica',
    'Nancy', 'Nathan', 'Neil', 'Nicholas', 'Nicole', 'Nina', 'Noah', 'Nora',
    'Oliver', 'Oscar', 'Owen',
    'Patricia', 'Patrick', 'Paul', 'Penny', 'Peter', 'Philip',
    'Rachel', 'Ralph', 'Raymond', 'Rebecca', 'Richard', 'Robert', 'Roger', 'Ruth',
    'Samuel', 'Sandra', 'Sarah', 'Scott', 'Sharon', 'Simon', 'Sophia', 'Steven',
    'Teresa', 'Thomas', 'Timothy', 'Tina', 'Tracy', 'Tyler',
    'Walter', 'Wendy', 'William', 'Winston',
  ],
  city: [
    'Atlanta', 'Austin', 'Albuquerque', 'Anchorage',
    'Boston', 'Baltimore', 'Boise', 'Buffalo',
    'Chicago', 'Charlotte', 'Cleveland', 'Columbus',
    'Dallas', 'Denver', 'Detroit', 'Durham',
    'El Paso', 'Eugene',
    'Fresno', 'Fort Worth',
    'Greensboro', 'Glendale',
    'Houston', 'Honolulu', 'Hartford',
    'Indianapolis', 'Irvine',
    'Jacksonville', 'Jersey City',
    'Kansas City', 'Knoxville',
    'Las Vegas', 'Los Angeles', 'Louisville', 'Lexington',
    'Memphis', 'Miami', 'Milwaukee', 'Minneapolis',
    'Nashville', 'Newark', 'Norfolk', 'New Orleans',
    'Oakland', 'Orlando', 'Omaha',
    'Philadelphia', 'Phoenix', 'Pittsburgh', 'Portland',
    'Raleigh', 'Richmond', 'Riverside',
    'Sacramento', 'San Diego', 'Seattle', 'St Louis',
    'Tampa', 'Tucson', 'Tulsa',
    'Washington', 'Wichita',
  ],
  country: [
    'Argentina', 'Australia', 'Austria', 'Afghanistan',
    'Belgium', 'Brazil', 'Bulgaria', 'Bahamas', 'Barbados',
    'Canada', 'Chile', 'China', 'Colombia', 'Cuba', 'Croatia', 'Costa Rica',
    'Denmark', 'Dominican Republic',
    'Ecuador', 'Egypt', 'Ethiopia', 'Estonia',
    'Finland', 'France', 'Fiji',
    'Germany', 'Greece', 'Guatemala', 'Ghana',
    'Honduras', 'Hungary', 'Haiti',
    'India', 'Indonesia', 'Ireland', 'Israel', 'Italy', 'Iran', 'Iraq',
    'Japan', 'Jordan', 'Jamaica',
    'Kenya', 'Kuwait', 'Kazakhstan',
    'Latvia', 'Lebanon', 'Libya', 'Lithuania',
    'Malaysia', 'Mexico', 'Morocco', 'Mongolia',
    'Nepal', 'Netherlands', 'Nigeria', 'Norway', 'New Zealand',
    'Oman',
    'Pakistan', 'Panama', 'Peru', 'Poland', 'Portugal', 'Paraguay',
    'Romania', 'Russia', 'Rwanda',
    'Spain', 'Sweden', 'Switzerland', 'Singapore', 'Serbia',
    'Thailand', 'Turkey', 'Tunisia', 'Taiwan',
    'Ukraine', 'Uruguay',
    'Venezuela', 'Vietnam',
    'Wales',
  ],
  animal: [
    'Alligator', 'Ant', 'Armadillo', 'Antelope', 'Alpaca',
    'Bear', 'Beaver', 'Butterfly', 'Buffalo', 'Bat', 'Badger', 'Bison',
    'Cat', 'Cheetah', 'Chicken', 'Cow', 'Crab', 'Chameleon', 'Chinchilla',
    'Deer', 'Dog', 'Dolphin', 'Duck', 'Donkey', 'Dragonfly',
    'Eagle', 'Elephant', 'Elk', 'Emu',
    'Fox', 'Frog', 'Flamingo', 'Falcon', 'Ferret',
    'Giraffe', 'Goat', 'Gorilla', 'Goose', 'Gecko', 'Gazelle',
    'Horse', 'Hamster', 'Hawk', 'Hippo', 'Heron', 'Hedgehog',
    'Iguana', 'Impala', 'Ibis',
    'Jaguar', 'Jellyfish', 'Jackal',
    'Kangaroo', 'Koala', 'Kingfisher',
    'Lion', 'Llama', 'Lobster', 'Leopard', 'Lemur', 'Lynx',
    'Monkey', 'Moose', 'Mouse', 'Mole', 'Manatee',
    'Narwhal', 'Newt', 'Nightingale',
    'Octopus', 'Ostrich', 'Otter', 'Owl', 'Ocelot',
    'Penguin', 'Pig', 'Puma', 'Panda', 'Parrot', 'Pelican', 'Porcupine',
    'Rabbit', 'Raccoon', 'Raven', 'Robin', 'Rattlesnake', 'Rhinoceros',
    'Shark', 'Snake', 'Spider', 'Squirrel', 'Swan', 'Salamander', 'Seahorse',
    'Tiger', 'Turtle', 'Toucan', 'Tapir',
    'Walrus', 'Wolf', 'Whale', 'Wombat', 'Woodpecker', 'Weasel',
  ],
  food: [
    'Apple', 'Avocado', 'Asparagus', 'Artichoke', 'Almond',
    'Banana', 'Bread', 'Broccoli', 'Brownie', 'Burrito', 'Bagel', 'Biscuit',
    'Cake', 'Carrot', 'Cereal', 'Cheese', 'Chicken', 'Cookie', 'Corn', 'Croissant',
    'Donut', 'Dumpling', 'Danish',
    'Egg', 'Enchilada', 'Eclair',
    'Fries', 'Fudge', 'Falafel', 'Focaccia',
    'Granola', 'Grapes', 'Grilled Cheese', 'Gumbo',
    'Hamburger', 'Honey', 'Hot Dog', 'Hummus',
    'Ice Cream',
    'Jam', 'Jerky', 'Jelly',
    'Kale', 'Ketchup', 'Kebab',
    'Lasagna', 'Lemon', 'Lettuce', 'Lobster bisque',
    'Mango', 'Muffin', 'Mushroom', 'Macaroni', 'Mousse',
    'Nachos', 'Noodles', 'Nutella',
    'Oatmeal', 'Orange', 'Oreos', 'Olive',
    'Pancake', 'Pasta', 'Pizza', 'Pretzel', 'Pie', 'Popcorn',
    'Quiche', 'Quinoa',
    'Rice', 'Ravioli', 'Risotto',
    'Salad', 'Sandwich', 'Spaghetti', 'Steak', 'Sushi', 'Scone', 'Sorbet',
    'Taco', 'Toast', 'Tomato', 'Tiramisu', 'Truffle',
    'Waffle', 'Watermelon', 'Wonton',
  ],
  thing: [
    'Alarm', 'Album', 'Anchor', 'Apron',
    'Blanket', 'Book', 'Bottle', 'Box', 'Broom', 'Bucket', 'Belt', 'Brush',
    'Candle', 'Chair', 'Clock', 'Couch', 'Cup', 'Curtain', 'Clipboard',
    'Door', 'Desk', 'Drill', 'Dustpan',
    'Envelope', 'Eraser', 'Extension cord',
    'Fan', 'Flag', 'Fork', 'Frame', 'Flashlight',
    'Glove', 'Guitar', 'Globe',
    'Hat', 'Hammer', 'Hook', 'Hose',
    'Iron', 'Ice pack',
    'Jacket', 'Jar', 'Journal',
    'Key', 'Knife', 'Kite', 'Kettle',
    'Lamp', 'Ladder', 'Lock', 'Lunchbox',
    'Mirror', 'Mop', 'Mug', 'Magnet',
    'Nail', 'Napkin', 'Needle', 'Notebook',
    'Oven',
    'Pen', 'Pillow', 'Plate', 'Plunger', 'Poster',
    'Rug', 'Ruler', 'Rope', 'Remote',
    'Scissors', 'Shelf', 'Soap', 'Sponge', 'Spoon', 'Stool', 'Stapler',
    'Towel', 'Trash can', 'Thermos', 'Tape',
    'Umbrella',
    'Vase',
    'Wrench', 'Wallet', 'Whistle',
  ],
  sport: [
    'Archery', 'Baseball', 'Basketball', 'Bowling', 'Boxing', 'Badminton',
    'Cricket', 'Cycling', 'Curling', 'Climbing',
    'Diving', 'Dodgeball', 'Darts',
    'Fencing', 'Football', 'Fishing',
    'Golf', 'Gymnastics',
    'Hockey', 'Hiking', 'Handball',
    'Ice Skating',
    'Javelin', 'Judo', 'Jogging',
    'Karate', 'Kayaking', 'Kickboxing',
    'Lacrosse', 'Luge',
    'Marathon',
    'Netball',
    'Orienteering',
    'Polo', 'Parkour', 'Pickleball',
    'Rowing', 'Rugby', 'Running', 'Rock climbing',
    'Sailing', 'Skiing', 'Soccer', 'Softball', 'Swimming', 'Surfing', 'Skateboarding',
    'Tennis', 'Track', 'Triathlon',
    'Volleyball',
    'Weightlifting', 'Wrestling', 'Water polo',
  ],
  clothing: [
    'Anorak',
    'Blouse', 'Boots', 'Belt', 'Blazer', 'Beanie', 'Bermuda shorts',
    'Cardigan', 'Cap', 'Coat', 'Corset', 'Camisole',
    'Dress', 'Dungarees',
    'Earmuffs',
    'Fleece', 'Fedora',
    'Gloves', 'Gown', 'Galoshes',
    'Hat', 'Hoodie', 'High heels',
    'Jacket', 'Jeans', 'Jumpsuit',
    'Khakis', 'Kimono',
    'Leggings', 'Loafers',
    'Mittens', 'Moccasins', 'Muumuu',
    'Necktie',
    'Overalls', 'Oxford shoes',
    'Pants', 'Parka', 'Polo', 'Poncho',
    'Robe', 'Raincoat',
    'Sandals', 'Scarf', 'Shorts', 'Skirt', 'Socks', 'Sweater', 'Suspenders',
    'Tie', 'Tank top', 'Turtleneck', 'Trench coat', 'Tunic',
    'Vest',
    'Windbreaker',
  ],
  show: [
    'American Idol', 'Avatar',
    'Breaking Bad', 'Brooklyn Nine-Nine', 'Bridgerton',
    'Criminal Minds', 'CSI', 'Cobra Kai',
    'Dexter', 'Downtown Abbey',
    'ER',
    'Friends', 'Frasier', 'Fleabag',
    'Game of Thrones', 'Gilmore Girls', 'Grey\'s Anatomy',
    'House', 'How I Met Your Mother',
    'Inception',
    'Jeopardy', 'Jurassic Park',
    'Kill Bill',
    'Law and Order', 'Lost',
    'Modern Family', 'Matrix',
    'NCIS',
    'Office', 'Ozark',
    'Parks and Recreation', 'Pulp Fiction',
    'Seinfeld', 'Stranger Things', 'Suits', 'Survivor', 'Shrek',
    'The Bachelor', 'The Simpsons', 'Titanic', 'Top Gun',
    'Walking Dead', 'Wheel of Fortune', 'Wednesday',
  ],
  occupation: [
    'Accountant', 'Architect', 'Artist', 'Astronaut', 'Analyst',
    'Baker', 'Barber', 'Biologist', 'Butler', 'Botanist',
    'Carpenter', 'Chef', 'Coach', 'Counselor', 'Cashier',
    'Dentist', 'Designer', 'Detective', 'Doctor', 'Dispatcher',
    'Editor', 'Electrician', 'Engineer', 'Economist',
    'Farmer', 'Firefighter', 'Florist',
    'Gardener', 'Geologist', 'Graphic designer',
    'Historian', 'Housekeeper',
    'Inspector', 'Interpreter',
    'Janitor', 'Journalist', 'Judge',
    'Lawyer', 'Librarian', 'Locksmith', 'Lifeguard',
    'Mechanic', 'Musician', 'Manager',
    'Nurse', 'Navigator', 'Nutritionist',
    'Optometrist',
    'Painter', 'Paramedic', 'Pharmacist', 'Pilot', 'Plumber', 'Professor', 'Programmer',
    'Receptionist', 'Reporter', 'Researcher',
    'Scientist', 'Surgeon', 'Secretary',
    'Teacher', 'Therapist', 'Translator', 'Technician',
    'Veterinarian',
    'Writer', 'Welder',
  ],
  flower: [
    'Amaryllis', 'Aster', 'Azalea',
    'Begonia', 'Bluebell', 'Buttercup',
    'Carnation', 'Chrysanthemum', 'Crocus', 'Camellia',
    'Daffodil', 'Dahlia', 'Daisy',
    'Edelweiss',
    'Forget-me-not', 'Freesia',
    'Gardenia', 'Geranium', 'Gladiolus',
    'Hibiscus', 'Hyacinth', 'Hydrangea',
    'Iris',
    'Jasmine', 'Jonquil',
    'Lavender', 'Lily', 'Lotus',
    'Magnolia', 'Marigold',
    'Narcissus',
    'Orchid',
    'Pansy', 'Peony', 'Petunia', 'Poppy', 'Primrose',
    'Rose',
    'Snapdragon', 'Sunflower', 'Sweet pea',
    'Tulip',
    'Violet',
    'Wisteria',
  ],
  tree: [
    'Ash', 'Aspen', 'Alder',
    'Birch', 'Beech', 'Banyan',
    'Cedar', 'Cherry', 'Cypress', 'Chestnut',
    'Dogwood',
    'Elm', 'Eucalyptus',
    'Fir',
    'Ginkgo',
    'Hemlock', 'Hickory', 'Holly',
    'Ironwood',
    'Juniper',
    'Larch', 'Linden',
    'Maple', 'Magnolia', 'Mahogany',
    'Nutmeg',
    'Oak', 'Olive',
    'Palm', 'Pine', 'Poplar',
    'Redwood',
    'Spruce', 'Sequoia', 'Sycamore',
    'Teak',
    'Walnut', 'Willow',
  ],
  color: [
    'Amber', 'Aqua', 'Azure',
    'Beige', 'Black', 'Blue', 'Bronze', 'Brown', 'Burgundy',
    'Cerulean', 'Chartreuse', 'Coral', 'Cream', 'Crimson', 'Cyan',
    'Denim',
    'Ebony', 'Emerald',
    'Fuchsia',
    'Gold', 'Gray', 'Green',
    'Hazel',
    'Indigo', 'Ivory',
    'Jade',
    'Khaki',
    'Lavender', 'Lemon', 'Lilac', 'Lime',
    'Magenta', 'Maroon', 'Mauve', 'Mint',
    'Navy',
    'Olive', 'Orange', 'Orchid',
    'Peach', 'Pearl', 'Pink', 'Plum', 'Purple',
    'Red', 'Rose', 'Ruby', 'Rust',
    'Sage', 'Salmon', 'Sapphire', 'Scarlet', 'Silver', 'Slate',
    'Tan', 'Teal', 'Turquoise',
    'Violet',
    'White', 'Wine',
  ],
  instrument: [
    'Accordion',
    'Banjo', 'Bass', 'Bassoon', 'Bugle',
    'Cello', 'Clarinet', 'Cornet', 'Cymbal',
    'Drum',
    'Euphonium',
    'Fiddle', 'Flute', 'French horn',
    'Guitar', 'Glockenspiel',
    'Harmonica', 'Harp',
    'Kazoo', 'Keyboard',
    'Lute', 'Lyre',
    'Mandolin', 'Maracas',
    'Oboe', 'Organ',
    'Piano', 'Piccolo',
    'Recorder',
    'Saxophone', 'Sitar',
    'Trombone', 'Trumpet', 'Tuba',
    'Ukulele',
    'Viola', 'Violin',
    'Xylophone',
  ],
  car: [
    'Acura', 'Alfa Romeo', 'Aston Martin', 'Audi',
    'Bentley', 'BMW', 'Buick',
    'Cadillac', 'Chevrolet', 'Chrysler', 'Citroën',
    'Dodge', 'Ducati',
    'Ferrari', 'Fiat', 'Ford',
    'Genesis', 'GMC',
    'Honda', 'Hyundai', 'Hummer',
    'Infiniti',
    'Jaguar', 'Jeep',
    'Kia',
    'Lamborghini', 'Land Rover', 'Lexus', 'Lincoln',
    'Maserati', 'Mazda', 'Mercedes', 'Mini',
    'Nissan',
    'Oldsmobile',
    'Porsche', 'Pontiac',
    'Ram', 'Rolls Royce',
    'Saab', 'Saturn', 'Subaru', 'Suzuki',
    'Tesla', 'Toyota',
    'Volkswagen', 'Volvo',
  ],
  holiday: [
    'April Fools',
    'Boxing Day',
    'Christmas', 'Cinco de Mayo', 'Columbus Day',
    'Diwali',
    'Easter', 'Earth Day',
    'Fathers Day', 'Fourth of July',
    'Good Friday', 'Groundhog Day',
    'Halloween', 'Hanukkah',
    'Independence Day',
    'Juneteenth',
    'Kwanzaa',
    'Labor Day', 'Lunar New Year',
    'Martin Luther King Day', 'Memorial Day', 'Mothers Day',
    'New Years',
    'Passover', 'Presidents Day',
    'Ramadan',
    'St Patricks Day',
    'Thanksgiving',
    'Valentines Day', 'Veterans Day',
  ],
  toy: [
    'Action figure',
    'Barbie', 'Blocks', 'Board game',
    'Cards', 'Clay', 'Coloring book', 'Crayons',
    'Doll', 'Dominoes', 'Drone',
    'Etch A Sketch',
    'Frisbee', 'Figurine',
    'Game Boy',
    'Hot Wheels', 'Hula hoop',
    'Jack in the box', 'Jigsaw puzzle',
    'Kaleidoscope', 'Kite',
    'Lego', 'Lincoln Logs',
    'Marbles', 'Mr Potato Head',
    'Nerf gun',
    'Play-Doh', 'Puppet', 'Puzzle',
    'Robot', 'Rubiks Cube',
    'Slinky', 'Stuffed animal',
    'Teddy bear', 'Top', 'Train set',
    'Uno',
    'Water gun', 'Whistle',
    'Yo-yo',
  ],
  superhero: [
    'Ant-Man', 'Aquaman',
    'Batman', 'Black Panther', 'Black Widow',
    'Captain America', 'Catwoman', 'Cyclops',
    'Daredevil', 'Deadpool',
    'Elektra',
    'Flash',
    'Green Arrow', 'Green Lantern',
    'Hawkeye', 'Hulk',
    'Iron Man',
    'Jean Grey',
    'Nightcrawler',
    'Phoenix',
    'Robin', 'Rogue',
    'Spider-Man', 'Storm', 'Superman',
    'Thor',
    'Vision',
    'Wolverine', 'Wonder Woman',
  ],
  mythological: [
    'Angel',
    'Banshee', 'Basilisk',
    'Centaur', 'Cerberus', 'Chimera', 'Cyclops',
    'Dragon', 'Dwarf',
    'Elf',
    'Fairy', 'Fenrir',
    'Gargoyle', 'Genie', 'Ghost', 'Gnome', 'Goblin', 'Golem', 'Griffin',
    'Harpy', 'Hydra',
    'Imp',
    'Jinn',
    'Kraken',
    'Leprechaun', 'Leviathan',
    'Medusa', 'Mermaid', 'Minotaur',
    'Nymph',
    'Ogre', 'Oracle',
    'Pegasus', 'Phoenix', 'Pixie',
    'Satyr', 'Siren', 'Sphinx',
    'Thunderbird', 'Titan', 'Troll',
    'Unicorn',
    'Vampire', 'Valkyrie',
    'Werewolf', 'Witch', 'Wizard', 'Wraith',
  ],
  emotion: [
    'Admiration', 'Anger', 'Anxiety', 'Awe',
    'Bliss', 'Boredom',
    'Calm', 'Compassion', 'Confusion', 'Contentment', 'Courage', 'Curiosity',
    'Delight', 'Despair', 'Disgust', 'Dread',
    'Ecstasy', 'Embarrassment', 'Empathy', 'Envy', 'Euphoria', 'Excitement',
    'Fear', 'Frustration', 'Fury',
    'Glee', 'Gratitude', 'Grief', 'Guilt',
    'Happiness', 'Hatred', 'Hope', 'Horror', 'Humiliation',
    'Irritation',
    'Jealousy', 'Joy',
    'Kindness',
    'Loneliness', 'Love',
    'Melancholy',
    'Nervousness', 'Nostalgia',
    'Optimism',
    'Panic', 'Passion', 'Peace', 'Pride',
    'Rage', 'Relief', 'Remorse',
    'Sadness', 'Satisfaction', 'Shame', 'Shock', 'Sorrow', 'Surprise', 'Sympathy',
    'Terror', 'Trust',
    'Wonder', 'Worry',
  ],
  brand: [
    'Adidas', 'Amazon', 'Apple', 'Audi',
    'BMW', 'Burberry',
    'Chanel', 'Coca-Cola', 'Costco',
    'Dell', 'Disney',
    'Etsy',
    'Facebook', 'Ferrari', 'Ford',
    'Gap', 'Google', 'Gucci',
    'Honda', 'HP',
    'IBM', 'IKEA', 'Intel',
    'Jeep',
    'Kelloggs', 'KFC',
    'Lego', 'Levis', 'LG',
    'McDonalds', 'Microsoft',
    'Netflix', 'Nike', 'Nintendo',
    'Oracle',
    'Pepsi', 'Porsche', 'Prada', 'Puma',
    'Rolex',
    'Samsung', 'Sony', 'Starbucks', 'Subway',
    'Target', 'Tesla', 'Toyota',
    'Uber', 'Under Armour',
    'Visa', 'Volkswagen',
    'Walmart',
    'Xbox',
  ],
  body_of_water: [
    'Amazon', 'Adriatic Sea', 'Arabian Sea', 'Arctic Ocean', 'Atlantic Ocean',
    'Baltic Sea', 'Bay of Bengal', 'Black Sea', 'Bering Sea',
    'Caribbean Sea', 'Caspian Sea', 'Coral Sea',
    'Dead Sea', 'Delaware River',
    'English Channel', 'Erie',
    'Gulf of Mexico',
    'Hudson Bay',
    'Indian Ocean',
    'Java Sea',
    'Lake Michigan', 'Lake Superior',
    'Mediterranean', 'Mississippi',
    'Nile', 'North Sea',
    'Ohio River',
    'Pacific Ocean', 'Persian Gulf',
    'Red Sea', 'Rhine',
    'South China Sea', 'Suez Canal',
    'Thames', 'Tigris',
    'Volga',
    'Yangtze',
  ],
};

function categorize(category: string): string {
  const lower = category.toLowerCase();
  if (lower.includes('name') || lower.includes('people') || lower.includes('famous') || lower.includes('athlete') || lower.includes('leader') || lower.includes('comedian') || lower.includes('scientist')) return 'name';
  if (lower.includes('city') || lower.includes('cities')) return 'city';
  if (lower.includes('vacation') || lower.includes('spot') || lower.includes('restaurant')) return 'city';
  if (lower.includes('countr') || lower.includes('language')) return 'country';
  if (lower.includes('animal') || lower.includes('insect') || lower.includes('dog breed') || lower.includes('zoo')) return 'animal';
  if (lower.includes('bird')) return 'animal';
  if (lower.includes('fish') || lower.includes('reptile') || lower.includes('seafood')) return 'animal';
  if (lower.includes('flower')) return 'flower';
  if (lower.includes('tree')) return 'tree';
  if (lower.includes('color')) return 'color';
  if (lower.includes('instrument')) return 'instrument';
  if (lower.includes('car') && lower.includes('brand')) return 'car';
  if (lower.includes('holiday')) return 'holiday';
  if (lower.includes('toy') || lower.includes('board game')) return 'toy';
  if (lower.includes('superhero') || lower.includes('villain') || lower.includes('cartoon') || lower.includes('fairy tale')) return 'superhero';
  if (lower.includes('mytholog') || lower.includes('creature')) return 'mythological';
  if (lower.includes('emotion')) return 'emotion';
  if (lower.includes('brand') || lower.includes('store') || lower.includes('app') || lower.includes('website')) return 'brand';
  if (lower.includes('bodies of water') || lower.includes('water')) return 'body_of_water';
  if (lower.includes('food') || lower.includes('fruit') || lower.includes('vegetable') || lower.includes('breakfast') || lower.includes('dessert') || lower.includes('snack') || lower.includes('candy') || lower.includes('pizza') || lower.includes('pasta') || lower.includes('cereal') || lower.includes('baked') || lower.includes('ice cream') || lower.includes('sandwich') || lower.includes('condiment') || lower.includes('beverage')) return 'food';
  if (lower.includes('sport') || lower.includes('hobb') || lower.includes('dance') || lower.includes('game')) return 'sport';
  if (lower.includes('cloth') || lower.includes('wear') || lower.includes('head')) return 'clothing';
  if (lower.includes('tv') || lower.includes('show') || lower.includes('movie') || lower.includes('song') || lower.includes('character') || lower.includes('book') || lower.includes('magazine') || lower.includes('musical group')) return 'show';
  if (lower.includes('occupation') || lower.includes('job') || lower.includes('major')) return 'occupation';
  return 'thing';
}

function getMatchingWords(bank: string[], letter: string): string[] {
  const l = letter.toUpperCase();
  return bank.filter((w) => w.toUpperCase().startsWith(l));
}

export interface AIPlayer {
  id: string;
  name: string;
  skill: number;
}

const AI_NAMES_BY_DIFFICULTY: Record<AIDifficulty, string[]> = {
  easy: ['Rookie Bot'],
  medium: ['Bot Alpha', 'Bot Beta'],
  hard: ['CPU Omega', 'CPU Sigma', 'CPU Delta'],
};

const DIFFICULTY_CONFIG: Record<AIDifficulty, { count: number; skillMin: number; skillMax: number }> = {
  easy: { count: 1, skillMin: 0.25, skillMax: 0.45 },
  medium: { count: 2, skillMin: 0.45, skillMax: 0.65 },
  hard: { count: 3, skillMin: 0.70, skillMax: 0.90 },
};

export function createAIPlayers(count?: number, difficulty: AIDifficulty = 'medium'): AIPlayer[] {
  const config = DIFFICULTY_CONFIG[difficulty];
  const n = count ?? config.count;
  const names = AI_NAMES_BY_DIFFICULTY[difficulty];
  return Array.from({ length: n }, (_, i) => ({
    id: `ai-${i + 1}`,
    name: names[i] ?? `Bot ${i + 1}`,
    skill: config.skillMin + Math.random() * (config.skillMax - config.skillMin),
  }));
}

export function generateAIAnswers(
  ai: AIPlayer,
  categories: string[],
  letter: string,
): string[] {
  return categories.map((cat) => {
    if (Math.random() > ai.skill) return '';

    const bankKey = categorize(cat);
    const bank = WORD_BANK[bankKey] ?? WORD_BANK['thing']!;
    const matches = getMatchingWords(bank, letter);

    if (matches.length === 0) return '';

    return matches[Math.floor(Math.random() * matches.length)]!;
  });
}
